artifacts_root: data

data_ingestion:
  root_dir: data/data_ingestion
  source_URL: https://www.kaggle.com/datasets/emmarex/plantdisease/download?datasetVersionNumber=1
  local_data_file: data/data_ingestion/data.zip
  unzip_dir: data/data_ingestion
