artifacts_root: data

data_ingestion:
  root_dir: data/data_ingestion
  source_URL: https://github.com/nirmitktripathii/plant_disease_classification/raw/main/data.zip
  local_data_file: data/data_ingestion/data.zip
  unzip_dir: data/data_ingestion

prepare_base_model:
  root_dir: data/prepare_base_model
  base_model_path: data/prepare_base_model/base_model.h5
  updated_base_model_path: data/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: data/prepare_callbacks
  tensorboard_root_log_dir: data/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: data/prepare_callbacks/checkpoint_dir/model.h5
# training:
#   root_dir: data/training
#   trained_model_path: data/training/model.h5
